In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('train.csv')

In [5]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [3]:
from ydata_profiling import ProfileReport #install ydata_profiling using pip install ydata-profiling
prof = ProfileReport(df)                  # creating an object of ProfileReport and passing df as argument
prof.to_file(output_file='output.html')   # converting prof to html file

c:\Users\aniru\AppData\Local\Programs\Python\Python312\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Summarize dataset:  74%|███████▎  | 14/19 [00:00<00:00, 17.95it/s, Calculate auto correlation]  c:\Users\aniru\AppData\Local\Programs\Python\Python312\Lib\site-packages\ydata_profiling\model\correlations.py:66: UserWarning: There was an attempt to calculate the auto correlation, but this failed.
To hide this warning, disable the calculation
(using `df.profile_report(correlations={"auto": {"calculate": False}})`
If this is problematic for your use case, please report this as an issue:
https://github.com/ydataai/ydata-profiling/issues
(include the error message: 'could not convert string to float: 'S'')
  warnings.warn(
Summarize dataset:  89%|████████▉ | 42/47 [00:03<00:00,  7.18it/s, Missing diagram heatmap]         c:\Users\aniru\AppData\Local\Programs\Python\Python312\Lib\site-packages\seaborn\matrix.py:260: FutureWarning: Format strings passed to MaskedConstant are ignored, but in future may error or produce different behavior
  annotation = ("{:" + self.fmt + "}").format(val)
c:\Users\aniru\AppData\Local\Programs\Python\Python312\Lib\site-packages\ydata_profiling\model\missing.py:78: UserWarning: There was an attempt to generate the Heatmap missing values diagrams, but this failed.
To hide this warning, disable the calculation
(using `df.profile_report(missing_diagrams={"Heatmap": False}`)
If this is problematic for your use case, please report this as an issue:
https://github.com/ydataai/ydata-profiling/issues
(include the error message: 'could not convert string to float: '--'')
  warnings.warn(
Summarize dataset: 100%|██████████| 47/47 [00:03<00:00, 12.30it/s, Completed]
Generate report structure: 100%|██████████| 1/1 [00:04<00:00,  4.01s/it]
Render HTML: 100%|██████████| 1/1 [00:01<00:00,  1.31s/it]
Export report to file: 100%|██████████| 1/1 [00:00<00:00, 99.05it/s]